### ISSUE TITLE
Seeking help about parameters

### ISSUE THREAD

**Issue by lhxone** [misiekc/polygonRSA#1]
I want to simulate the rectangle, but I can't figure out how to input the `particleType` and `particleAttributes`  parameters. 

The example input.txt file is:

```
particleType = RegularRoundedPolygonAlgebraic            # shape to pack
particleAttributes = standard 3 1 0.5   # particle dependent attributes - here [number of sides] [side length] [rounding radius]
```

What shoud I do if I want to simulate the rectangle ?

@misiekc Could you please help me

**Comment by PKua007** [comment]
The `RoundedPolygonAlgebraic` class should be used to simulate rectangles since `RegularRounded...` classes support only regular polygons, while the former one supports arbitrary shapes. `particleAttributes` are described in `shape/shapes/RoundedPolygonAlgebraic.cpp:36-53`. In your case, assuming that one side has length `[a]`, the second has length `[b]` and the rounding radius is `[r]`, input file fields should read

```
particleType = RoundedPolygonAlgebraic
particleAttributes = [r] 4 xy [a/2] [b/2] [-a/2] [b/2] [-a/2] [-b/2] [a/2] [-b/2] 4 0 1 2 3
```

So, for example for a=1, b=2, r=0.2 it would be

```
particleAttributes = 0.2 4 xy 0.5 1 -0.5 1 -0.5 -1 0.5 -1 4 0 1 2 3
```

The second argument `4` specifies number of vertices, `xy` specifies format of coordinates - in that case x and y coordinates - it is followed by the vertices, then `4` specifies number of edges and `0 1 2 3` are the indices of subsequent vertices joined cyclicly to form a rectangle.

If you would like all shapes to be documented, you can create a separate issue with a request.

**Comment by lhxone** [comment]
Thank you a lot for your reply. I have set the proper parameters and get the image. But I still have another little problem. How to set the parameters when the polymers bind to the substrate in a certain direction as shown in the figure below？

![NKVK5.png](https://s1.328888.xyz/2022/07/16/NKVK5.png)

**Comment by lhxone** [comment]
Thank you a lot for your reply. I have set the proper parameters and get the image. But I still have another little problem. How to set the parameters when the polymers bind to the substrate in a certain direction as shown in the figure below？

![](https://camo.githubusercontent.com/e9ec4aa0be18bafee932f56140c36a4f4ae1927edc46ffec0281e42d2c9d5ac2/68747470733a2f2f73312e3332383838382e78797a2f323032322f30372f31362f4e4b564b352e706e67)

@PKua007
